"use client";

import { createContext, useState } from "react";
import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const AppContext = createContext();

export default function RootLayout({ children }) {
  const [account, setAccount] = useState("");

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex justify-center items-center">
          <div className="hide-scrollbar overflow-y-scroll overflow-x-hidden w-[390px] h-[844px] bg-white rounded-3xl  border-neutral-800 border-4">
            <AppContext.Provider value={{ account, setAccount }}>
              {children}
            </AppContext.Provider>
          </div>
        </div>
      </body>
    </html>
  );
}
